### ISSUE TITLE
Hello, your work is excellent. Could you upload the *The waterloo_sqoe4_feature.zip* file? I can't find it.

### ISSUE THREAD

**Issue by 851682852** [Leo-rojo/Analysis-of-Waterloo-IV-QoE-dataset#1]
thank you!

**Comment by Leo-rojo** [comment]
Hello,

I've confirmed that the original license is CC BY 4.0, which allows sharing with proper citation. You can find a portion of the original dataset relevant to the proposed analysis in the WaterlooIV partial database folder. Please remember to cite the original work as outlined in the README.md file.
